services:
  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ragkurikulum
    ports:
      - 6024:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
